apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: milvus
  namespace: ingress-apisix
spec:
  http:
    - name: milvus
      match:
        hosts:
          - milvus.d
        paths:
          - /*
      backends:
        - serviceName: my-release-milvus
          servicePort: 19530
      plugins:
        - name: redirect
          enable: true
          config:
            http_to_https: true
        - name: grpc-web
          enable: true