kind: ClusterConfiguration
apiVersion: kubeadm.k8s.io/v1beta4
kubernetesVersion: v1.32.0
imageRepository: registry.cn-hangzhou.aliyuncs.com/google_containers
networking:
  podSubnet: "10.244.0.0/16,fd00:10:244::/64" # 指定 Pod 网络范围，包括 IPv4 和 IPv6 子网
  serviceSubnet: "10.96.0.0/12,fd00:10:96::/108" # 指定 Service 网络范围，包括 IPv4 和 IPv6 子网
apiServer:
  extraArgs:
    - name: "service-node-port-range"
      value: "100-50000" # 定义 NodePort 的端口范围
---
kind: KubeletConfiguration
apiVersion: kubelet.config.k8s.io/v1beta1
cgroupDriver: systemd
authentication:
  anonymous:
    enabled: false
  webhook:
    enabled: true
authorization:
  mode: Webhook
---
apiVersion: kubeadm.k8s.io/v1beta4
kind: InitConfiguration
nodeRegistration:
  #criSocket: unix:///run/containerd/containerd.sock
  criSocket: unix:///run/cri-dockerd.sock
  #kubeletExtraArgs:
---
apiVersion: kubeproxy.config.k8s.io/v1alpha1
kind: KubeProxyConfiguration
mode: ipvs
