apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frpc
  name: frpc
  namespace: tools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frpc
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: frpc
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: frpc
          image: jybl/frpc
          imagePullPolicy: IfNotPresent
          command:
            - frpc
            - "-url"
            - "https://localhost"
