apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: tcp-route
spec:
  stream:
    - name: tcp-route-rule
      protocol: TCP
      match:
        ingressPort: 9100
      backends:
        - serviceName: tcp-server
          servicePort: 8080
    - name: udp-route-rule
      protocol: UDP
      match:
        ingressPort: 9200
      backends:
        - serviceName: udp-server
          servicePort: 53