global:
  hosts:
    #domain: gitlab.dev
    #hostSuffix: staging
    https: false
    externalIP:
    gitlab:
      name: gitlab.tools
      https: false
    registry:
      name: registry.gitlab.tools
      https: false
    minio:
      name: minio.gitlab.tools
      https: false
    smartcard:
      name: smartcard.gitlab.tools
    kas:
      name: kas.gitlab.tools
    pages:
      name: pages.gitlab.tools
      https: false
  ingress:
    provider: apisix
  psql:
    host: postgres.tools
    # serviceName: postgres
    port: 5432
    database: gitlab
    username: postgres
    applicationName:
    preparedStatements: false
    databaseTasks: true
    password:
      useSecret: false
      secret: gitlab-postgres
      key: psql-password
      file: /password
  redis:
    host: redis.tools
    #serviceName: redis
    port: 6379
    password:
      enabled: false
      secret: gitlab-redis
      key: redis-password
    scheme:
  grafana:
    enabled: false
  gitaly:
    internal:
      names:
        - default
    authToken:
      secret: gitaly-secret
      key: token
    tls:
      enabled: false
      secretName: gitlab-gitaly-tls
  rails:
    bootsnap:
      enabled: true
  workhorse:
    serviceName: workhorse
    host: workhorse.tools
    port: 8181
  pages:
    enabled: true
    accessControl:
    path:
    host: gitlab.tools
    port:
    https: false
    externalHttp:
    externalHttps:
    artifactsServer:
    objectStore:
      enabled:
      bucket:
      proxy_download: true
      connection:
        secret:
        key:
    localStore:
      enabled: false
      path:
    apiSecret:
      secret:
      key:
  serviceAccount:
    enabled: false
    create: false
  ingress:
    enabled: false
    configureCertmanager: false
redis:
  install: false
postgresql:
  intall: false
registry:
  enabled: false
