name: hello
description: Dart gRPC sample client and server.
homepage: https://github.com/dart-lang/grpc-dart

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  async: ^2.2.0

dev_dependencies:
  test: ^1.24.1