
## Deploy a Prometheus instance
##
prometheus:
  prometheusSpec:
    # Additional volumes on the output StatefulSet definition.
    volumes:
      - name: etcd-certs
        hostPath:
          path: /root/certs/etcd
    # Additional VolumeMounts on the output StatefulSet definition.
    volumeMounts:
      - name: etcd-certs
        mountPath: /etc/prometheus/secrets/etcd-client-cert/
        readOnly: true

kubeEtcd:
  serviceMonitor:
    scheme: https
    caFile: /etc/prometheus/secrets/etcd-client-cert/ca.crt
    certFile: /etc/prometheus/secrets/etcd-client-cert/server.crt
    keyFile: /etc/prometheus/secrets/etcd-client-cert/server.key

grafana:
  grafana.ini:
    security:
      allow_embedding: true
    auth.anonymous:
      enabled: true
  ## Timezone for the default dashboards
  ## Other options are: browser or a specific timezone, i.e. Europe/Luxembourg
  ##
  defaultDashboardsTimezone: Asia/Shanghai

  adminPassword: prom-operator

  extraConfigmapMounts: []
  # - name: certs-configmap
  #   mountPath: /etc/grafana/ssl/
  #   configMap: certs-configmap
  #   readOnly: true
