apiVersion: apisix.apache.org/v2beta3
kind: ApisixRoute
metadata:
  name: grafana
  namespace: monitoring
spec:
  http:
    - name: grafana
      match:
        hosts:
          - grafana.hoper.xyz
        paths:
          - /*
      backends:
        - serviceName: kube-prometheus-grafana
          servicePort: 80
          resolveGranularity: service
      websocket: true
      plugins:
        - name: redirect
          enable: true
          config:
            http_to_https: true

---
apiVersion: apisix.apache.org/v2beta3
kind: ApisixRoute
metadata:
  name: prometheus
  namespace: monitoring
spec:
  http:
    - name: prometheus
      match:
        hosts:
          - prometheus.hoper.xyz
        paths:
          - /*
      backends:
        - serviceName: kube-prometheus-kube-prome-prometheus
          servicePort: 9090
          resolveGranularity: service
      plugins:
        - name: redirect
          enable: true
          config:
            http_to_https: true

