//+build !noasm !appengine
// AUTO-GENERATED BY C2GOASM -- DO NOT EDIT

TEXT ·_Avx2SsdInt16(SB), $0-24

    MOVQ a+0(FP), DI
    MOVQ b+8(FP), SI
    MOVQ c+16(FP), DX

    QUAD $0x00000000876ffec5     // vmovdqu    ymm0, yword [rdi]
    QUAD $0x0000000086f9fdc5     // vpsubw    ymm0, ymm0, yword [rsi]
    LONG $0xc0f5fdc5             // vpmaddwd    ymm0, ymm0, ymm0
    QUAD $0x00000000827ffec5; LONG $0x90909090 // vmovdqu    yword [rdx], ymm0
    VZEROUPPER
    RET
